name: Build, Push, and Run Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # AdoptOpenJDK distribution
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/demo-git-action:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-git-action:latest

      - name: Stop and remove existing container
        run: |
          if [ "$(docker ps -q -f name=demo-git-action)" ]; then
            docker stop demo-git-action
          fi
          if [ "$(docker ps -aq -f name=demo-git-action)" ]; then
            docker rm demo-git-action
          fi

      - name: Run Docker container
        run: docker run -d --name demo-git-action -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/demo-git-action:latest

